# Generated by Django 4.1.3 on 2022-11-22 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
    ]
